window.tailwind = window.tailwind || {};
window.tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline': '#6e797b',
        'on-secondary-fixed-variant': '#004e59',
        'on-primary-fixed': '#001f24',
        'surface-variant': '#e1e3df',
        'outline-variant': '#bec8ca',
        'inverse-primary': '#7ed3e1',
        'error-container': '#ffdad6',
        'error': '#ba1a1a',
        'surface-bright': '#f8faf6',
        'secondary': '#146875',
        'surface': '#f8faf6',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#001f28',
        'primary': '#006570',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e1e3df',
        'primary-container': '#1c7f8c',
        'background': '#f8faf6',
        'surface-container-high': '#e7e9e5',
        'primary-fixed': '#9bf0fe',
        'on-primary-fixed-variant': '#004f58',
        'secondary-fixed': '#a7eefd',
        'on-surface-variant': '#3e494a',
        'on-secondary-fixed': '#001f25',
        'surface-dim': '#d8dbd7',
        'tertiary-container': '#477b8c',
        'surface-container': '#eceeeb',
        'on-secondary': '#ffffff',
        'on-surface': '#191c1a',
        'surface-tint': '#006874',
        'inverse-surface': '#2e312f',
        'on-tertiary-container': '#f7fcff',
        'surface-container-low': '#f2f4f0',
        'on-primary-container': '#f3fdff',
        'inverse-on-surface': '#eff1ed',
        'tertiary': '#2c6273',
        'secondary-container': '#a4ebfa',
        'tertiary-fixed': '#b6ebfe',
        'tertiary-fixed-dim': '#9acee1',
        'on-secondary-container': '#1b6c79',
        'on-background': '#191c1a',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#7ed3e1',
        'on-tertiary-fixed-variant': '#124d5d',
        'secondary-fixed-dim': '#8bd1e0'
      },
      fontFamily: {
        'headline': ['Manrope'],
        'body': ['Inter'],
        'label': ['Space Grotesk']
      },
      borderRadius: {'DEFAULT': '0.25rem', 'lg': '0.5rem', 'xl': '0.75rem', 'full': '9999px'},
    },
  },
};
